name: swirl_shortvideosdk
description: "Short Video Sdk."
version: 1.0.0
homepage: https://github.com/SefaliMi/shortvideosdkflutter.git

environment:  
  sdk: '>=3.2.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  video_player: ^2.9.1
  scrollable_positioned_list: ^0.2.3
  chewie: ^1.7.5  
  smooth_page_indicator: ^1.2.0+3
  http: ^1.2.0
  dio: ^5.7.0
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/images/emoji_fire.png
    - assets/images/emoji_trophy.png
    - assets/images/icon_burst_new.png
    - assets/images/icon_rating.png
    - assets/images/icon_chat.png
    - assets/images/eye.png
    - assets/images/icon_cart.png
    - assets/images/icon_horizontal_dort.png
    - assets/images/close.png
    - assets/images/add_to_cart.png
    - assets/images/play.png
    - assets/images/pause.png
    - assets/images/indicator.png
    - assets/images/ic_person.png
    - assets/images/down_arrow.png
    - assets/images/expand_diagonal_line.png
    - assets/images/up_arrow.png
    - assets/images/pin.png
    - assets/images/plus.png
    - assets/images/minus.png
    - assets/images/pictureinpicture.png
    - assets/images/download.png  
    - assets/images/copy_link.png  
    - assets/images/sms.png
    - assets/images/mail.png
    - assets/images/twitter.png
    - assets/images/facebook.png
    - assets/images/whatsapp.png
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: CircularStd
       fonts:
        - asset: assets/fonts/CircularStd-Book.otf
          weight: 400  # Book weight (Regular)
        - asset: assets/fonts/CircularStd-Black.otf
        - asset: assets/fonts/CircularStd-Bold.otf     
          weight: 700  # Bold weight   
        - asset: assets/fonts/CircularStd-Medium.otf
          weight: 500  # Medium weight
        - asset: assets/fonts/CircularStd-Light.otf
          weight: 300 # Light
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
